mongodb:
  enabled: true
  host: mongodb:27017
  user:
  password:
  adminPassword:

prefixPath: ''

keptnSpecVersion: latest

nats:
  nameOverride: keptn-nats-cluster
  nats.cluster.replicas: 3

  natsbox:
    enabled: false

apiGatewayNginx:
  type: ClusterIP
  port: 80
  nodePort: 31090
  image:
    repository: nginxinc/nginx-unprivileged
    tag: 1.19.4-alpine

remediationService:
  image:
    repository: keptn/remediation-service
    tag: ''

apiService:
  image:
    repository: keptn/api
    tag: ''
  config:
    maxAuthRequestsPerSecond: '1.0'
    maxAuthRequestBurst: '2'

bridge:
  image:
    repository: keptn/bridge2
    tag: ''
  cliDownloadLink:
  integrationsPageLink:
  secret:
    enabled: true
  versionCheck:
    enabled: true
  showApiToken:
    enabled: true
  installationType:
  lookAndFeelUrl:
  oauth:
    enabled: false
    discovery: ''
    secureCookie: false
    trustProxy: ''

distributor:
  metadata:
    hostname:
    namespace:
  image:
    repository: keptn/distributor
    tag: ''

shipyardController:
  image:
    repository: keptn/shipyard-controller
    tag: ''
  config:
    taskStartedWaitDuration: "10m"
    uniformIntegrationTTL: "48h"

secretService:
  image:
    repository: keptn/secret-service
    tag: ''

configurationService:
  image:
    repository: keptn/configuration-service
    tag: ''
  # storage and storageClass are the settings for the PVC used by the configuration-storage
  storage: 100Mi
  storageClass:

mongodbDatastore:
  image:
    repository: keptn/mongodb-datastore
    tag: ''

lighthouseService:
  image:
    repository: keptn/lighthouse-service
    tag: ''

statisticsService:
  image:
    repository: keptn/statistics-service
    tag: ''

approvalService:
  image:
    repository: keptn/approval-service
    tag: ''

webhookService:
  image:
    repository: keptn/webhook-service
    tag: ''

alpine:
  image:
    repository: alpine
    tag: '3.13'

ingress:
  enabled: false
  annotations: {}
  host: {}
  path: /
  pathType: Prefix
  tls:
    []
