name: Unit Tests
on:
  push:
    branches: [ feature/2716/unit-tests-as-github-action ]
  pull_request:
    branches: [ master ]
jobs:
  unit-tests-go:
    name: Unit-Tests-Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test cli
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
        working-directory: ./cli
      - name: Test api
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./handlers/... ./ws/... ./utils/...
        working-directory: ./api
      - name: Test jmeter svc
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ./jmeter-service